version: "3.9"

services:
  db:
    image: mysql:8.0
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: todos_test
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 30

  app-tests:
    build:
      context: .
      target: test-runner   # ← usamos el stage de tests
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DB: todos_test
    depends_on:
      db:
        condition: service_healthy
