services:
  app:
    build: .
    environment:
      PORT: 3000
      SQLITE_DB_LOCATION: /data/todo.db
    volumes:
      - todo-data:/data
    expose:
      - "3000"

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - app
    ports:
      - "9000:9000"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  todo-data:
