version: "3.9"

services:
  db:
    image: mysql:8.0
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: todo
      MYSQL_PASSWORD: supersecret
      MYSQL_DB: todos
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootsecret"]
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - "3307:3306"

  app:
    build: .
    environment:
      PORT: 3000
      
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: todo
      MYSQL_PASSWORD: supersecret
      MYSQL_DB: todos
    depends_on:
      db:
        condition: service_healthy
    
    volumes:
      - todo-data:/data
    expose:
      - "3000"

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - app
    ports:
      - "9000:9000"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  db-data:
  todo-data:
