name: CI (compose tests + build)

on:
  workflow_dispatch:
  pull_request:
    branches: [ develop, master ]
  push:
    branches: [ develop ]

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Usamos Node solo para validar que el lockfile instala (rápido feedback si el lock está roto)
      - name: Set up Node & validate lockfile
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - name: Install deps (lockfile validation)
        run: |
          corepack enable
          corepack prepare yarn@1.22.22 --activate
          yarn install --frozen-lockfile --network-timeout 600000

      # Corre tests con compose de test (MySQL + app-tests)
      - name: Run tests with Docker Compose
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
        run: |
          docker compose -f docker-compose.test.yml up --build --exit-code-from app-tests
          docker compose -f docker-compose.test.yml down -v

      # Solo si los tests pasan, construimos la imagen de prod (tu Dockerfile final)
      - name: Build production image
        run: docker build -t todoapp-ci:latest .
