name: CI (build & basic checks)

on:
  pull_request:
    branches: [ develop, master ]
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Enable Yarn 1.x with Corepack
        run: |
          corepack enable
          corepack prepare yarn@1.22.22 --activate
          yarn -v

      - name: Install deps 
        run: yarn install --frozen-lockfile --network-timeout 600000

      - name: Run tests (con cobertura si existe)
        run: |
          if yarn -s run | grep -q "\"test\""; then
            # intenta con jest/nyc si lo tienes
            yarn test --coverage || yarn test || true
          else
            echo "No test script found in package.json, skipping."
          fi

      - name: Build Docker image
        run: docker build -t todoapp-ci:check .

      # ← ← Guarda el build de tu app si existe
      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: |
            build/**
            dist/**
            coverage/**
            *.log
          if-no-files-found: ignore
          retention-days: 14
